version: '3.9'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mundilfari
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mundilfari -U myuser || exit 1"]
      timeout: 3s
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/conf:/conf:ro
    environment:
      - DB_SOURCE=postgresql://myuser:mypass@postgres:5432/mundilfari?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
