// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: service_mundilfari.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MundilfariClient is the client API for Mundilfari service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MundilfariClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type mundilfariClient struct {
	cc grpc.ClientConnInterface
}

func NewMundilfariClient(cc grpc.ClientConnInterface) MundilfariClient {
	return &mundilfariClient{cc}
}

func (c *mundilfariClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Mundilfari/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mundilfariClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Mundilfari/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MundilfariServer is the server API for Mundilfari service.
// All implementations must embed UnimplementedMundilfariServer
// for forward compatibility
type MundilfariServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedMundilfariServer()
}

// UnimplementedMundilfariServer must be embedded to have forward compatible implementations.
type UnimplementedMundilfariServer struct {
}

func (UnimplementedMundilfariServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMundilfariServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedMundilfariServer) mustEmbedUnimplementedMundilfariServer() {}

// UnsafeMundilfariServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MundilfariServer will
// result in compilation errors.
type UnsafeMundilfariServer interface {
	mustEmbedUnimplementedMundilfariServer()
}

func RegisterMundilfariServer(s grpc.ServiceRegistrar, srv MundilfariServer) {
	s.RegisterService(&Mundilfari_ServiceDesc, srv)
}

func _Mundilfari_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MundilfariServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mundilfari/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MundilfariServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mundilfari_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MundilfariServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mundilfari/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MundilfariServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mundilfari_ServiceDesc is the grpc.ServiceDesc for Mundilfari service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mundilfari_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Mundilfari",
	HandlerType: (*MundilfariServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Mundilfari_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Mundilfari_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_mundilfari.proto",
}
